- name: clone node-sonos-http-api repo
  git:
      repo: https://github.com/rtimmons/node-sonos-http-api.git
      clone: yes
      dest: /home/pi/node-sonos-http-api
      # TODO: vars?
      version: 876a47a68881ae555b9a3200188df77d25e20a0c

- name: Install node-sonos-http-api node.js package
  shell: npm install --no-save
  args:
    chdir: /home/pi/node-sonos-http-api

- name: copy node-sonos-http-api config
  copy:
    src: presets
    dest: /home/pi/node-sonos-http-api
    owner: pi

- name: copy node-sonos-http-api systemd unit file
  become_user: root
  become: true
  copy:
    src: node-sonos-http-api.service
    dest: /etc/systemd/system/node-sonos-http-api.service
    owner: root
    group: root
    mode: 0664

- name: start node-sonos-http-api service
  become_user: root
  become: true
  service:
    name: node-sonos-http-api
    state: restarted
    enabled: yes