- id: 'scene_bedroom_off'
  alias: scene_bedroom_off
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_off
  condition: []
  action:
  - scene: scene.scene_bedroom_off

- id: '1579460095280'
  alias: scene_bedroom_medium
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_medium
  condition: []
  action:
  - scene: scene.scene_bedroom_medium

- id: '1579461078882'
  alias: scene_bedroom_high
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_high
  condition: []
  action:
  - scene: scene.scene_bedroom_high
