- id: living_outlet_slider_on
  alias: living_outlet_slider_on
  trigger:
  - platform: webhook
    webhook_id: living_outlet_slider_on
  action:
  - data: {}
    entity_id: switch.living_outlet_slider
    service: switch.turn_on
- id: living_outlet_slider_off
  alias: living_outlet_slider_off
  trigger:
  - platform: webhook
    webhook_id: living_outlet_slider_off
  action:
  - data: {}
    entity_id: switch.living_outlet_slider
    service: switch.turn_off
  - data:
      brightness: 50
    entity_id: light.ge_jasco_products_46203_in_wall_smart_dimmer_level
    service: light.turn_on
