- id: bedroom_switch_bedside_doubletap_up
  alias: bedroom_switch_bedside_doubletap_up
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_switch_bedside
      scene_id: 1
  condition: []
  action:
  - scene: scene.bedroom_switch_bedside_doubletap_up

- id: bedroom_switch_bedside_doubletap_down
  alias: bedroom_switch_bedside_doubletap_down
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_switch_bedside
      scene_id: 2
  condition: []
  action:
  - scene: scene.bedroom_switch_bedside_doubletap_down

- id: 'scene_bedroom_off'
  alias: scene_bedroom_off
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_off
  condition: []
  action:
  - scene: scene.scene_bedroom_off

- id: '1579460095280'
  alias: scene_bedroom_medium
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_medium
  condition: []
  action:
  - scene: scene.scene_bedroom_medium

- id: '1579461078882'
  alias: scene_bedroom_high
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_high
  condition: []
  action:
  - scene: scene.scene_bedroom_high
