- id: living_outlet_slider_on
  alias: living_outlet_slider_on
  trigger:
  - platform: webhook
    webhook_id: living_outlet_slider_on
  action:
  - data: {}
    entity_id: switch.living_outlet_slider
    service: switch.turn_on
- id: living_outlet_slider_off
  alias: living_outlet_slider_off
  trigger:
  - platform: webhook
    webhook_id: living_outlet_slider_off
  action:
  - data: {}
    entity_id: switch.living_outlet_slider
    service: switch.turn_off
- id: '1578867518792'
  alias: scene_living_on
  description: scene_living_on
  trigger:
  - platform: webhook
    webhook_id: scene_living_on
  condition: []
  action:
  - scene: scene.scene_living_on
- id: '1578867781833'
  alias: scene_living_off
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_living_off
  condition: []
  action:
  - scene: scene.scene_living_off
