- id: living_outlet_slider_on
  alias: living_outlet_slider_on
  trigger:
  - platform: webhook
    webhook_id: living_outlet_slider_on
  action:
  - data: {}
    entity_id: switch.living_outlet_slider
    service: switch.turn_on
- id: living_outlet_slider_off
  alias: living_outlet_slider_off
  trigger:
  - platform: webhook
    webhook_id: living_outlet_slider_off
  action:
  - data: {}
    entity_id: switch.living_outlet_slider
    service: switch.turn_off
- id: '1579460095280'
  alias: scene_bedroom_medium
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_medium
  condition: []
  action:
  - scene: scene.scene_bedroom_medium
