## Bedroom Switches

- id: bedroom_switch_bedside_doubletap_up
  alias: bedroom_switch_bedside_doubletap_up
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_switch_bedside
      scene_id: 1
      scene_data: 7860
  condition: []
  action:
  - scene: scene.bedroom_switch_bedside_doubletap_up

- id: bedroom_switch_bedside_doubletap_down
  alias: bedroom_switch_bedside_doubletap_down
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_switch_bedside
      scene_id: 2
      scene_data: 7860
  condition: []
  action:
  - scene: scene.bedroom_switch_bedside_doubletap_down

- id: bedroom_switch_closet_doubletap_up
  alias: bedroom_switch_closet_doubletap_up
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_switch_closet
      scene_id: 1
      scene_data: 7860
  condition: []
  action:
  - scene: scene.bedroom_switch_closet_doubletap_up

- id: bedroom_switch_closet_doubletap_down
  alias: bedroom_switch_closet_doubletap_down
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.bedroom_switch_closet
      scene_id: 2
      scene_data: 7860
  condition: []
  action:
  - scene: scene.bedroom_switch_closet_doubletap_down

## Bedroom Dashboard Buttons

- id: scene_bedroom_off
  alias: scene_bedroom_off
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_off
  condition: []
  action:
  - scene: scene.scene_bedroom_off

- id: scene_bedroom_medium
  alias: scene_bedroom_medium
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_medium
  condition: []
  action:
  - scene: scene.scene_bedroom_medium

- id: scene_bedroom_high
  alias: scene_bedroom_high
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_bedroom_high
  condition: []
  action:
  - scene: scene.scene_bedroom_high

## Closet Dashboard Buttons

- id: scene_closet_off
  alias: scene_closet_off
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_closet_off
  condition: []
  action:
  - scene: scene.scene_closet_off

- id: scene_closet_medium
  alias: scene_closet_medium
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_closet_medium
  condition: []
  action:
  - scene: scene.scene_closet_medium

- id: scene_closet_medium
  alias: scene_closet_high
  description: ''
  trigger:
  - platform: webhook
    webhook_id: scene_closet_high
  condition: []
  action:
  - scene: scene.scene_closet_high

## Office Switch

- id: office_switch_main_doubletap_up
  alias: office_switch_main_doubletap_up
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.office_switch_main
      scene_id: 1
  condition: []
  action:
  - scene: scene.office_switch_main_doubletap_up

- id: office_switch_main_doubletap_down
  alias: office_switch_main_doubletap_down
  trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.office_switch_main
      scene_id: 2
  condition: []
  action:
  - scene: scene.office_switch_main_doubletap_down
