# node 1 is the dongle
# node 2 is the living slider

entities:
  - name: bathroom_light_sauna
    type: hue light
  - name: bathroom_light_shower
    type: hue light
  - name: bathroom_light_vanityleft
    type: hue light
  - name: bathroom_light_vanityright
    type: hue light

  - name: bedroom_light_desk
    type: hue light
  - name: bedroom_light_dresser
    type: hue light color
  - name: bedroom_outlet_flamingo
    type: outlet
    node_id: 4
  - name: bedroom_switch_bedside
    type: dimmer switch 46203
    node_id: 3
    on_up_double: scene_bedroom_high
    on_down_double: scene_bedroom_off
  - name: bedroom_switch_closet
    type: dimmer switch 46203
    node_id: 5
    on_up_double: scene_bedroom_medium
    on_down_double: scene_bedroom_off

  - name: entry_switch_kitchen
    type: dimmer switch 46203
    node_id: 11
    on_up_double: scene_kitchen_high
    on_down_double: scene_kitchen_off

  - name: global_switch_hall
    type: dimmer switch 46203
    node_id: 15
    on_up_double: scene_hall_high
    on_down_double: scene_hall_off

  - name: kitchen_light_lower
    type: hue light color
  - name: kitchen_light_upper
    type: hue light color
  - name: kitchen_switch_dining
    type: dimmer switch 46203
    node_id: 9
    on_up_double: scene_dining_high
    on_down_double: scene_dining_off

  - name: living_light_floor
    type: hue light color
  - name: living_outlet_slider
    type: outlet
    node_id: 2
  - name: living_switch_deck
    type: dimmer switch 14291
    node_id: 14
#    on_up_double: scene_deck_high
#    on_down_double: scene_deck_off

  - name: office_light_sidetable
    type: hue light color
  - name: office_outlet_pianolight
    type: outlet
    node_id: 6
  - name: office_outlet_pipelight
    type: outlet
    node_id: 7
  - name: office_switch_main
    type: dimmer switch ws100
    node_id: 8
    on_up_double: scene_office_high
    on_down_double: scene_office_off

event_names:
  'dimmer switch 46203':
    up: {scene_id: 1}
    down: {scene_id: 2}
    single: {scene_data: 7680}
    double: {scene_data: 7860}
    triple: {scene_data: 7920}
    hold_start: {scene_data: 7800}
    hold_end: {scene_data: 7740}

state_templates:

  dimmer_high:
    brightness: 255
    # friendly_name: bedroom_switch_bedside
    # node_id: 3
    state: 'on'
    supported_features: 1
    value_id: '72057594093076481'
    value_index: 0
    value_instance: 1
  dimmer_medium:
    brightness: 49
    # friendly_name: bedroom_switch_bedside
    # node_id: 3
    state: 'on'
    supported_features: 1
    value_id: '72057594093076481'
    value_index: 0
    value_instance: 1
  dimmer_off:
    brightness: 49
    # friendly_name: bedroom_switch_bedside
    # node_id: 3
    state: 'on'
    supported_features: 1
    value_id: '72057594093076481'
    value_index: 0
    value_instance: 1

  hue_default:
    min_mireds: 153
    max_mireds: 500
    effect_list: colorloop,random
    brightness: 254
    color_temp: 346
    effect: none
    # friendly_name: office_light_sidetable
    supported_features: 63
    state: 'on'
  hue_medium:
    min_mireds: 153
    max_mireds: 500
    effect_list: colorloop,random
    brightness: 100
    color_temp: 454
    effect: none
    # friendly_name: office_light_sidetable
    supported_features: 63
    state: 'on'
  hue_off:
    min_mireds: 153
    max_mireds: 500
    effect_list: colorloop,random
    brightness: 254
    color_temp: 346
    effect: none
    # friendly_name: office_light_sidetable
    supported_features: 63
    state: 'off'

  outlet_on:
    # friendly_name: bedroom_outlet_flamingo
    # node_id: 4
    state: 'on'
    value_id: '72057594109837312'
    value_index: 0
    value_instance: 1
  outlet_off:
    # friendly_name: bedroom_outlet_flamingo
    # node_id: 4
    state: 'off'
    value_id: '72057594109837312'
    value_index: 0
    value_instance: 1



# Rooms:
# bathroom, closet, move, bedroom, living, kitchen, office, guest_bathroom
  

scenes:
  - name: scene_bathroom_high
    entities:
      bathroom_light_sauna: hue_default
      bathroom_light_shower: hue_default
      bathroom_light_vanityleft: hue_default
      bathroom_light_vanityright: hue_default
  - name: scene_bathroom_medium
    entities:
      bathroom_light_sauna: hue_medium
      bathroom_light_shower: hue_medium
      bathroom_light_vanityleft: hue_medium
      bathroom_light_vanityright: hue_medium
  - name: scene_bathroom_off
    entities:
      bathroom_light_sauna: hue_off
      bathroom_light_shower: hue_off
      bathroom_light_vanityleft: hue_off
      bathroom_light_vanityright: hue_off

  - name: scene_bedroom_high
    entities:
      bedroom_switch_bedside: dimmer_high
      bedroom_outlet_flamingo: outlet_on
      bedroom_light_dresser: hue_default
  - name: scene_bedroom_medium
    entities:
      bedroom_switch_bedside: dimmer_medium
      bedroom_outlet_flamingo: outlet_off
      bedroom_light_dresser: dimmer_medium
  - name: scene_bedroom_off
    entities:
      bedroom_switch_bedside: dimmer_off
      bedroom_outlet_flamingo: outlet_off
      bedroom_light_dresser: hue_off

  - name: scene_office_high
    entities:
      office_light_sidetable: hue_default
      office_outlet_pipelight: outlet_off
      office_outlet_pianolight: outlet_on

  - name: scene_office_medium
    entities:
      office_light_sidetable: hue_medium
      office_outlet_pipelight: outlet_on
      office_outlet_pianolight: outlet_off

  - name: scene_office_off
    entities:
      office_light_sidetable: hue_off
      office_outlet_pipelight: outlet_off
      office_outlet_pianolight: outlet_off

