---

- name: install dependencies
  become_user: root
  become: true
  apt:
    pkg: [libffi-dev, libssl-dev, python3-nacl, libopenzwave1.5-dev]
    state: present

- name: install master open-zwave configs
  git:
    repo: 'https://github.com/OpenZWave/open-zwave.git'
    dest: /home/pi/open-zwave


- name: install global pip packages
  become_user: root
  become: true
  pip:
    executable: pip3.8
    name:
    - python_openzwave
    - urwid
    - homeassistant
    - homeassistant-pyozw
    # these are packages that home-assistant would normally install "on-demand"
    # but I want to do it ahead of time as much as possible especially since
    # this is the only real way to pass in the -j4 flag.
    - "HAP-python==2.6.0"
    - "homekit[IP]==0.15.0"
    - "python-nest==4.1.0"
    - "aiounifi==11"
    - "sqlalchemy==1.3.12"
    - "aiohttp_cors"
    - "hass-nabucasa==0.31"
    - "PyNaCl==1.3.0"
    - "mutagen==1.43.0"
    - "gTTS-token==1.1.3"
    - "pyMetno==0.4.6"
    - "colorlog==4.0.2"
    state: present
  environment:
    MAKEFLAGS: '-j4'

- name: copy home-assistant systemd unit file
  become_user: root
  become: true
  copy:
    src: home-assistant.service
    dest: /etc/systemd/system/home-assistant.service
    owner: root
    group: root
    mode: 0664

- name: start home-assistant service
  become_user: root
  become: true
  service:
    name: home-assistant
    state: restarted
    enabled: yes
