---

- name: copy smarthome repo
  synchronize:
      group: no
      checksum: yes
      copy_links: yes
      links: yes
      partial: yes
      perms: yes
      recursive: yes
      times: yes
      delete: yes
      src: "{{ playbook_dir }}/.."
      dest: /home/pi/repo
