- name: set hostname
  hostname:
    name: "{{ secret.host.hostname }}"

- name: replace /etc/hosts
  template:
    src: etc_hosts.j2
    dest: /etc/hosts

- name: create new inventory file
  become: False
  local_action:
    module: template
    src: post_init.j2
    dest: "{{ playbook_dir }}/post_init.ini"
