---
secret:
    host:
        name: smarterhome # must be same as ↓ but without .local
        hostname: smarterhome.local
    ifttt:
        key: TODO
    smartthings:
        token: TODO # https://account.smartthings.com/tokens