- name: clone dasher repo
  become_user: smarthome
  become: yes
  git:
      repo: https://github.com/maddox/dasher
      clone: yes
      dest: /home/smarthome/dasher
      # TODO: vars?
      version: ef9d486996ea4eb196ca20098748f8504f2a807f
