# TODO: standardize yaml to 2 spaces

- name: install dependency packages
  apt:
      name: libpcap-dev
      state: latest

- name: clone dasher repo
  git:
      repo: https://github.com/maddox/dasher
      clone: yes
      dest: /home/pi/dasher
      # TODO: vars?
      version: ef9d486996ea4eb196ca20098748f8504f2a807f

- name: Install dasher node.js package
  shell: npm install
  args:
    chdir: /home/pi/dasher

- name: copy dasher config
  # TODO this is annoying
  become_user: root
  become: yes
  copy:
    src: config.js
    dest: /home/pi/dasher/config/config.json
    owner: smarthome

- name: copy systemd unit file
  copy:
    src: dasher.service
    dest: /etc/systemd/system/dasher.service
    owner: root
    group: root
    mode: 0664

- name: start dasher service
  service:
    name: dasher
    state: restarted

# use `sudo journalctl` to look at logs
