- name: install dependency packages
  apt:
      name: libpcap-dev
      state: latest

- name: clone dasher repo
  become_user: smarthome
  become: yes
  git:
      repo: https://github.com/maddox/dasher
      clone: yes
      dest: /home/smarthome/dasher
      # TODO: vars?
      version: ef9d486996ea4eb196ca20098748f8504f2a807f

- name: Install dasher node.js package
  become_user: smarthome
  become: yes
  shell: npm install
  args:
    chdir: /home/smarthome/dasher

- name: copy dasher config
  copy:
    src: config.js
    dest: /home/smarthome/dasher/config/config.json
    owner: smarthome

- name: copy systemd unit file
  copy:
    src: dasher.service
    dest: /etc/systemd/system/dasher.service
    owner: root
    group: root
    mode: 0664

- name: start dasher service
  service:
    name: dasher
    state: restarted

# use `sudo journalctl` to look at logs
