- name: install curl
  apt:
    name: curl
    state: present

- name: enable nodesource packages
  become_user: root
  become: yes
  shell:
    curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -;
    touch /tmp/nodesource
  args:
    creates: /tmp/nodesource

- name: install npm packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    -  libpcap-dev
    -  build-essential
    -  nodejs
    -  npm
