---
- name: apply roles
  hosts: post_init
  roles:
   # - { name: repo }
   - {name: smarthome}

  pre_tasks:
   - name: import secret vars
     include_vars: secret.yml
     no_log: true
   - name: import vars
     include_vars: main.yml
