- name: apply roles
  hosts: rypi
  roles:
  - { name: wifi, become: True, become_user: root }

  pre_tasks:
  - name: import secret vars
    include_vars: secret.yml
    # no_log: true
  - name: import vars
    include_vars: main.yml
